
package CapaPresentacion;
import CapaNegocio.Cliente;
import CapaNegocio.DetalleFactura;
import CapaNegocio.DetallePedido;
import CapaNegocio.Factura;
import CapaNegocio.Motorizado;
import CapaNegocio.Pedido;
import CapaNegocio.Producto;

public class Main2 extends javax.swing.JFrame {

    /**
     * Creates new form Main2
     */
    public Main2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txpShow = new javax.swing.JTextArea();
        btnEscribir = new javax.swing.JButton();
        btnLeer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtCodigoC = new javax.swing.JTextField();
        txtNombreC = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtCodigoF = new javax.swing.JTextField();
        txtTipoPago = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtCodigoDF = new javax.swing.JTextField();
        txtPrecioUnit = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtCantidadDF = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtCodigoPr = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecioRef = new javax.swing.JTextField();
        txtCodigoDP = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtCantidadDP = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtEstadoPedido = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtCodigoP = new javax.swing.JTextField();
        txtFechaPedido = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txtCodigoMotorizado = new javax.swing.JTextField();
        txtNombreMotorizado = new javax.swing.JTextField();
        txtCoelular = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txpShow.setColumns(20);
        txpShow.setRows(5);
        jScrollPane1.setViewportView(txpShow);

        btnEscribir.setText("Escribir");
        btnEscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscribirActionPerformed(evt);
            }
        });

        btnLeer.setText("Leer");
        btnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente");

        jLabel6.setText("Factura");

        jLabel7.setText("Detalle Factura");

        jLabel8.setText("Producto");

        jLabel9.setText("Contidad");

        jLabel10.setText("Codigo");

        jLabel11.setText("Precio Ref");

        jLabel12.setText("DetallePedido");

        jLabel13.setText("Codigo");

        jLabel14.setText("Nombre");

        jLabel18.setText("Direccion");

        jLabel23.setText("Telefono");

        jLabel27.setText("Codigo");

        jLabel28.setText("Tipo Pago");

        jLabel29.setText("Monto");

        jLabel30.setText("Codigo");

        jLabel34.setText("Precio Unit");

        jLabel35.setText("Subtotal");

        jLabel36.setText("Cantidad");

        jLabel37.setText("Codigo");

        jLabel38.setText("DescrIpcion");

        jLabel39.setText("Pedido");

        jLabel40.setText("Estado");

        jLabel41.setText("Codigo");

        jLabel42.setText("Fecha");

        jLabel43.setText("Motorizado");

        jLabel44.setText("Codigo");

        jLabel45.setText("Nombre");

        jLabel46.setText("Celular");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel37))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodigoPr, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioRef, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtCodigoF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel14)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel18)
                                                .addComponent(jLabel23)
                                                .addComponent(jLabel27)
                                                .addComponent(jLabel28)
                                                .addComponent(jLabel29)
                                                .addComponent(jLabel30)
                                                .addComponent(jLabel34)
                                                .addComponent(jLabel35)
                                                .addComponent(jLabel36))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtCodigoC)
                                                .addComponent(txtNombreC)
                                                .addComponent(txtDireccion)
                                                .addComponent(txtTelefono)
                                                .addComponent(txtMonto)
                                                .addComponent(txtTipoPago)
                                                .addComponent(txtCantidadDF, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                                .addComponent(txtSubtotal)
                                                .addComponent(txtPrecioUnit)
                                                .addComponent(txtCodigoDF))))
                                    .addComponent(jLabel6))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel9)))
                                            .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCodigoDP)
                                            .addComponent(txtCantidadDP)
                                            .addComponent(txtCodigoP)
                                            .addComponent(txtFechaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel43)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel44)
                                            .addComponent(jLabel40)
                                            .addComponent(jLabel45)
                                            .addComponent(jLabel46))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombreMotorizado, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtCodigoMotorizado, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtEstadoPedido)
                                            .addComponent(txtCoelular)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEscribir)
                        .addGap(58, 58, 58)
                        .addComponent(btnLeer)
                        .addGap(61, 61, 61)
                        .addComponent(btnEnviar)
                        .addGap(104, 104, 104)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtCodigoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)
                            .addComponent(txtCodigoPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtPrecioRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtCodigoDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtCodigoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtCantidadDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txtCodigoDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(txtPrecioUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(txtCantidadDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel39)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(txtCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(txtFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(txtCodigoMotorizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(txtNombreMotorizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(txtCoelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEnviar)
                            .addComponent(btnLeer)
                            .addComponent(btnEscribir))))
                .addGap(107, 107, 107))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscribirActionPerformed
        //Mensaje Confirmacion
        txpShow.setText("Los datos de la matricula se escribieron correctamente");
        // Needed
        String CodigoC =txtCodigoC.getText();
        String NombreC =txtNombreC.getText();
        String Direccion=txtDireccion.getText();
        String TelefonoC=txtTelefono.getText();
        String CodigoF=txtCodigoF.getText();
        String Descripcion=txtDescripcion.getText();
        String TipoP=txtTipoPago.getText();
        String Monto=txtMonto.getText();
        String CodigoDF=txtCodigoDF.getText();
        String PrecioUni=txtPrecioUnit.getText();
        String Subtotal=txtSubtotal.getText();
        String CantidadDF=txtCantidadDF.getText();
        String CodigoPr =txtCodigoPr.getText();
        String PrecioRf=txtPrecioRef.getText();
        String CodigoDP=txtCodigoDP.getText();
        String CantidadDP=txtCantidadDP.getText();
        String CodigoP=txtCodigoP.getText();
        String FechaP=txtFechaPedido.getText();
        String Estado=txtEstadoPedido.getText();
        String CodigoM=txtCodigoMotorizado.getText();
        String NombreMo=txtNombreMotorizado.getText();
        String Celular=txtCoelular.getText();
        
        //Declarar objeto
        Cliente cliente = new Cliente(CodigoC, NombreC,Direccion, TelefonoC);
        cliente.setCodCliente(CodigoC);
        cliente.setDireccionCliente(Direccion);
        cliente.setNombreCliente(NombreC);
        cliente.setTelefonoCliente(TelefonoC);
              
        DetalleFactura detallefa = new DetalleFactura(CodigoDF,Double.parseDouble(PrecioUni), Double.parseDouble(Subtotal),Float.parseFloat( CantidadDF));
        detallefa.setCantidadDetalleFactura(Float.parseFloat(CantidadDF));
        detallefa.setCodDetalleFactura(CodigoDF);
        detallefa.setPrecioRealUnitarioDetalleFactura(Double.parseDouble(CantidadDF));
        detallefa.setSubtotalDetalleFactura(Double.parseDouble(Subtotal));
        
        DetallePedido detallepe = new DetallePedido(CodigoP, Float.parseFloat(CantidadDP));
        detallepe.setCantidadDetallePedido(Float.parseFloat(CantidadDP));
        detallepe.setCodDetallePedido(CodigoP);
        
        Factura factura = new Factura(CodigoF, TipoP, Double.parseDouble(Monto));
        factura.setCodRegistroVenta(CodigoDP);
        factura.setMontoRegistroVenta(Double.parseDouble(Monto));
        factura.setTipoPagoRegistroVenta(TipoP);
        
        Motorizado moto = new Motorizado(CodigoM, NombreMo,Celular);
        moto.setCelularMotorizado(Celular);
        moto.setCodMotorizado(CodigoM);
        moto.setNombreMotorizado(NombreMo);

        Pedido pedido = new Pedido(CodigoP, FechaP, Estado);
        pedido.setCodPedido(CodigoP);
        pedido.setEstadoPedido(Estado);
        pedido.setFechaHoraPedido(FechaP);
        
        Producto producto = new Producto(CodigoPr, Descripcion,Double.parseDouble(PrecioRf));
        producto.setCodProducto(CodigoPr);
        producto.setDescripcionProducto(Descripcion);
        producto.setPrecioReferenciaProducto(Double.parseDouble(PrecioRf));


    }//GEN-LAST:event_btnEscribirActionPerformed

    private void btnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerActionPerformed
        String CodigoC =txtCodigoC.getText();
        String NombreC =txtNombreC.getText();
        String Direccion=txtDireccion.getText();
        String TelefonoC=txtTelefono.getText();
        String CodigoF=txtCodigoF.getText();
        String Descripcion=txtDescripcion.getText();
        String TipoP=txtTipoPago.getText();
        String Monto=txtMonto.getText();
        String CodigoDF=txtCodigoDF.getText();
        String PrecioUni=txtPrecioUnit.getText();
        String Subtotal=txtSubtotal.getText();
        String CantidadDF=txtCantidadDF.getText();
        String CodigoPr =txtCodigoPr.getText();
        String PrecioRf=txtPrecioRef.getText();
        String CodigoDP=txtCodigoDP.getText();
        String CantidadDP=txtCantidadDP.getText();
        String CodigoP=txtCodigoP.getText();
        String FechaP=txtFechaPedido.getText();
        String Estado=txtEstadoPedido.getText();
        String CodigoM=txtCodigoMotorizado.getText();
        String NombreMo=txtNombreMotorizado.getText();
        String Celular=txtCoelular.getText();

        txpShow.setText(
            String.join("\n"
                , "-Codigo de Cliente: "
                , CodigoC
                , ""
                , "-Nombre del Cliente: "
                , NombreC
                , ""
                , "-Direccion entrega"
                , Direccion
                , ""
                , "-Telefono del cliente"
                , TelefonoC
                , ""
                , "-Codigo Factura"
                , CodigoF
                , ""
                , "-Tipo Pago: "
                , TipoP
                , ""
                , "-Monto"
                , Monto
                , ""
                , "-Celular Vendedor: "
                , CodigoDF
                , ""    
                , "-Precio Unit: "
                , PrecioUni
                , ""
                , "-Subtotal"
                , Subtotal
                , ""
                , "-Cantidad"
                , CantidadDF
                , ""
                , "-Codigo Producto"
                , CodigoPr
                , ""
                , "-Descripcion: "
                , Descripcion
                , ""
                , "-Precio de Referencia: "
                , PrecioRf
                , ""
                , "-Codigo Detalle Pedido"
                , CodigoDP
                , ""
                , "-Cantidad Detalle Pedido"
                , CantidadDP
                , ""
                , "-Codigo Pedido"
                , CodigoP
                , ""
                , "-Fecha de Pedido: "
                , FechaP
                , ""
                , "-Estado Pedido"
                , Estado
                , ""
                , "-Codigo Motorizado"
                , CodigoM
                , ""
                , "-Nombre Motorizado: "
                , NombreMo
                , "" 
                , "-Celular del Motorizado: "
                , Celular
                , ""
            )
        );
    }//GEN-LAST:event_btnLeerActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        txpShow.setText("El pedido llegara en 30 minutos" );
           
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnEscribir;
    private javax.swing.JButton btnLeer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txpShow;
    private javax.swing.JTextField txtCantidadDF;
    private javax.swing.JTextField txtCantidadDP;
    private javax.swing.JTextField txtCodigoC;
    private javax.swing.JTextField txtCodigoDF;
    private javax.swing.JTextField txtCodigoDP;
    private javax.swing.JTextField txtCodigoF;
    private javax.swing.JTextField txtCodigoMotorizado;
    private javax.swing.JTextField txtCodigoP;
    private javax.swing.JTextField txtCodigoPr;
    private javax.swing.JTextField txtCoelular;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEstadoPedido;
    private javax.swing.JTextField txtFechaPedido;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JTextField txtNombreMotorizado;
    private javax.swing.JTextField txtPrecioRef;
    private javax.swing.JTextField txtPrecioUnit;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTipoPago;
    // End of variables declaration//GEN-END:variables
}
